#!/bin/bash
# Built-in volnoti notification plugin
notify_volume_volnoti() {
    # shellcheck disable=SC2034  # icon, summary, and body are part of the plugin interface but unused by volnoti
    local vol=$1 icon=$2 summary=$3 body=${*:4}
    local executable="${VOLNOTI_PATH:+${VOLNOTI_PATH%/}/}volnoti-show"

    command_exists "$executable" || { error "$executable not found. Please install it or set VOLNOTI_PATH to the correct path."; exit "$EX_UNAVAILABLE"; }

    if is_muted; then "$executable" -m "$vol"
    else "$executable" "$vol"; fi
}

